// src/ts/services/origin-labtalk.ts
// Round 96: Generate LabTalk (.ogs) script that auto-imports data
// and plots a graph matching the web preview's format/layout.
//
// Origin runs this script via command line: Origin64.exe -r script.ogs
// Origin opens, runs script, plot appears.

interface AxisRange {
  min?: number | null;
  max?: number | null;
  stepMajor?: number | null;
}

export interface OgsScriptOpts {
  /** Filename (e.g. 'HT-xxx.xlsx') located in Downloads folder */
  dataFilename: string;
  /** Category for choosing axis labels (e.g. 'xrd', 'raman', 'electrochem') */
  category: string;
  /** Title to put at top of graph (defaults to filename without extension) */
  title?: string;
  /** Axis labels to use (overrides category defaults) */
  xLabel?: string;
  yLabel?: string;
  /** User-set axis ranges from preview controls */
  axisSettings?: { x?: AxisRange; y?: AxisRange };
  /** Reverse X axis (e.g. for FTIR) */
  reverseX?: boolean;
  /** Log scale on X / Y axis */
  xLog?: boolean;
  yLog?: boolean;
}

const CATEGORY_LABELS: Record<string, { x: string; y: string }> = {
  xrd:        { x: '2-Theta (degree)',   y: 'Intensity (a.u.)' },
  raman:      { x: 'Raman shift (cm-1)', y: 'Intensity (a.u.)' },
  ftir:       { x: 'Wavenumber (cm-1)',  y: 'Transmittance (%)' },
  uvvis:      { x: 'Wavelength (nm)',    y: 'Absorbance (a.u.)' },
  'uvvis-drs': { x: 'Wavelength (nm)',    y: 'Reflectance (%)' },
  pl:         { x: 'Wavelength (nm)',    y: 'Intensity (a.u.)' },
  electrochem: { x: 'Potential (V)',     y: 'Current density (A/cm2)' },
  eds:        { x: 'Energy (keV)',       y: 'Counts' },
  xps:        { x: 'Binding Energy (eV)', y: 'Intensity (a.u.)' },
};

/**
 * Whether to use impMSExcel (xlsx) or impASC (csv/dat/txt/cor).
 */
function importCommand(filename: string): string {
  const lower = filename.toLowerCase();
  if (lower.endsWith('.xlsx') || lower.endsWith('.xls')) {
    return 'impMSExcel fname:="%(fname$)" options.SparkLines:=0';
  }
  // CSV/TSV/text: use impASC (Origin auto-detects delimiter)
  return 'impASC fname:="%(fname$)" options.ImpMode:=4';
}

/**
 * Strip extension from filename (HT-xxx.xlsx -> HT-xxx)
 */
function stripExt(filename: string): string {
  return filename.replace(/\.[^.]+$/, '');
}

/**
 * Escape LabTalk strings (single quote characters cause issues)
 */
function ltEscape(s: string): string {
  return s.replace(/"/g, '\\"').replace(/\n/g, ' ');
}

/**
 * Generate LabTalk script content. Returns string ready to write
 * as .ogs file.
 */
export function generateOgsScript(opts: OgsScriptOpts): string {
  const labels = CATEGORY_LABELS[opts.category] || { x: 'X', y: 'Y' };
  const xLabel = ltEscape(opts.xLabel || labels.x);
  const yLabel = ltEscape(opts.yLabel || labels.y);
  const baseName = stripExt(opts.dataFilename);
  const title = ltEscape(opts.title || `${opts.category.toUpperCase()} - ${baseName}`);

  const importCmd = importCommand(opts.dataFilename);

  // Axis range commands (only emit if user set value)
  const axisLines: string[] = [];
  if (opts.axisSettings?.x?.min != null) axisLines.push(`layer.x.from = ${opts.axisSettings.x.min};`);
  if (opts.axisSettings?.x?.max != null) axisLines.push(`layer.x.to = ${opts.axisSettings.x.max};`);
  if (opts.axisSettings?.x?.stepMajor != null) axisLines.push(`layer.x.inc = ${opts.axisSettings.x.stepMajor};`);
  if (opts.axisSettings?.y?.min != null) axisLines.push(`layer.y.from = ${opts.axisSettings.y.min};`);
  if (opts.axisSettings?.y?.max != null) axisLines.push(`layer.y.to = ${opts.axisSettings.y.max};`);
  if (opts.axisSettings?.y?.stepMajor != null) axisLines.push(`layer.y.inc = ${opts.axisSettings.y.stepMajor};`);

  if (opts.reverseX) {
    axisLines.push(`// Reverse X axis (e.g. FTIR convention)`);
    axisLines.push(`layer.x.opposite = 1;`);
  }
  if (opts.xLog) axisLines.push(`layer.x.type = 2;  // log scale`);
  if (opts.yLog) axisLines.push(`layer.y.type = 2;  // log scale`);

  const axisBlock = axisLines.length ? '\n// === Axis range / scale (from web preview) ===\n' + axisLines.join('\n') : '';

  return `// ====================================================================
// Auto-generated by LabBook BKU
// File: ${opts.dataFilename}
// Category: ${opts.category}
// ====================================================================
//
// This LabTalk script is run by Origin via:
//   Origin64.exe -rs run.section(path\\to\\this.OGS, Main)
//
// The [Main] section below is the entry point.
// It will:
//   1. Open a new workbook
//   2. Import the data file from %USERPROFILE%\\Downloads
//   3. Set column long names + units
//   4. Plot a line graph (col1=X, col2=Y)
//   5. Apply axis labels and ranges matching the web preview
//
// User can then edit the plot freely in Origin.

[Main]
// === Path to data file ===
// %YUFF% expands to User Files Folder. We use %USERPROFILE%\\Downloads.
string downloads$ = "%(USERPROFILE)\\Downloads";
string fname$ = downloads$ + "\\" + "${ltEscape(opts.dataFilename)}";

// === Create workbook + import data ===
newbook name:="${ltEscape(baseName)}";
${importCmd};

// === Set column long names ===
wks.col1.lname$ = "${xLabel}";
wks.col2.lname$ = "${yLabel}";
// Designate column types: 4 = X, 1 = Y
wks.col1.type = 4;
wks.col2.type = 1;

// === Plot line graph ===
// plot:=200 -> line plot
plotxy iy:=(1,2) plot:=200;

// === Apply graph styling ===
// Set page title
page.label$ = "${title}";

// Bottom X axis title
xb.text$ = "${xLabel}";
// Left Y axis title
yl.text$ = "${yLabel}";${axisBlock}

// === Plot line: teal color (matches web preview) ===
// Origin color index 14 = "Royal" (close to teal); use RGB for exact match
set %C -c color(13,148,136);
set %C -w 1500;  // line thickness 1.5 pt (units: 1/1000 pt)

// === Bring graph to front ===
win -a;
type "LabBook BKU: imported ${ltEscape(opts.dataFilename)} and created plot.";
`;
}

/**
 * Default script when category context isn't available (e.g. for
 * non-parseable files). Just imports + basic plot, no axis tweaks.
 */
export function generateMinimalOgsScript(filename: string): string {
  return generateOgsScript({
    dataFilename: filename,
    category: 'other',
  });
}
