@echo off
REM ============================================================
REM Round 95+96+97: LabBook BKU - Origin Lab integration installer
REM
REM Round 97 fix: launch command changed from `-r script.ogs`
REM (which opens Code Builder for editing) to:
REM   `-rs run.section("script.OGS", Main)`
REM (which actually EXECUTES the [Main] section of the script)
REM
REM Run as USER (NOT admin) so registry writes go to HKCU.
REM ============================================================

setlocal EnableDelayedExpansion
echo ==================================================================
echo  LabBook BKU - Cai dat tich hop Origin Lab (Round 97)
echo ==================================================================
echo.

REM -- Step 1: Locate Origin.exe --
set "ORIGIN_EXE="
for %%P in (
  "C:\Program Files\OriginLab\Origin2025\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2024\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2023\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2022\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2021\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2020\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2019\Origin64.exe"
  "C:\Program Files\OriginLab\Origin2018\Origin64.exe"
  "C:\Program Files (x86)\OriginLab\Origin2025\Origin.exe"
  "C:\Program Files (x86)\OriginLab\Origin2024\Origin.exe"
  "C:\Program Files (x86)\OriginLab\Origin2023\Origin.exe"
) do (
  if exist %%P (
    set "ORIGIN_EXE=%%~P"
    goto :found
  )
)

echo [!] Khong tim thay Origin.exe trong cac thu muc thong thuong.
echo     Vui long nhap day du duong dan toi Origin.exe (vi du:
echo     C:\Program Files\OriginLab\Origin2024\Origin64.exe)
echo.
set /p ORIGIN_EXE="Origin.exe path: "

if not exist "!ORIGIN_EXE!" (
  echo [ERROR] File khong ton tai: !ORIGIN_EXE!
  pause
  exit /b 1
)

:found
echo [OK] Tim thay Origin: "!ORIGIN_EXE!"
echo.

REM -- Step 2: Write wrapper batch script --
set "WRAPPER=%USERPROFILE%\labbook-origin.bat"
echo [Step 2] Tao wrapper script: !WRAPPER!
(
  echo @echo off
  echo REM Auto-generated by LabBook BKU install.bat (Round 97^)
  echo REM Handles 'labbook-origin://' protocol launches.
  echo REM   Mode 1: 'labbook-origin://file.xlsx'                ^(data only^)
  echo REM   Mode 2: 'labbook-origin://file.xlsx?withScript=1'   ^(auto-plot^)
  echo REM.
  echo REM Round 97: Mode 2 uses `-rs run.section(...)` instead of `-r ...`
  echo REM   `-r` opens script in Code Builder (edit mode) - wrong!
  echo REM   `-rs` actually EXECUTES the script's [Main] section
  echo.
  echo setlocal EnableDelayedExpansion
  echo set "ARG=%%~1"
  echo.
  echo REM Strip 'labbook-origin://' prefix
  echo set "FNAME=!ARG:labbook-origin://=!"
  echo if "!FNAME:~-1!"=="/" set "FNAME=!FNAME:~0,-1!"
  echo.
  echo REM Detect script mode by checking for '?withScript=1'
  echo set "SCRIPT_MODE=0"
  echo echo !FNAME! ^| findstr /C:"?withScript=1" ^>nul
  echo if not errorlevel 1 ^(
  echo   set "SCRIPT_MODE=1"
  echo   set "FNAME=!FNAME:?withScript=1=!"
  echo ^)
  echo.
  echo REM URL-decode common chars
  echo set "FNAME=!FNAME:%%20= !"
  echo set "FNAME=!FNAME:%%28=^(!"
  echo set "FNAME=!FNAME:%%29=^)!"
  echo.
  echo set "DATAFILE=%%USERPROFILE%%\Downloads\!FNAME!"
  echo if not exist "!DATAFILE!" ^(
  echo   echo [ERROR] Data file not found: !DATAFILE!
  echo   echo Hay tai file ve Downloads truoc khi mo Origin.
  echo   pause
  echo   exit /b 1
  echo ^)
  echo.
  echo REM Strip extension to get base name for .ogs lookup
  echo for %%%%I in ^("!DATAFILE!"^) do set "BASE=%%%%~dpnI"
  echo set "OGSFILE=!BASE!.ogs"
  echo.
  echo if "!SCRIPT_MODE!"=="1" if exist "!OGSFILE!" ^(
  echo   echo [LabBook] Executing auto-plot script: !OGSFILE!
  echo   REM Round 97 KEY FIX: -rs run.section(...) executes the script
  echo   REM Pass full path with quotes; section name is 'Main'
  echo   start "" "!ORIGIN_EXE!" -rs "run.section(!OGSFILE!, Main)"
  echo ^) else ^(
  echo   echo [LabBook] Launching Origin with data file: !DATAFILE!
  echo   start "" "!ORIGIN_EXE!" "!DATAFILE!"
  echo ^)
) > "!WRAPPER!"

if errorlevel 1 (
  echo [ERROR] Khong viet duoc !WRAPPER!
  pause
  exit /b 1
)
echo [OK] Wrapper script da tao
echo.

REM -- Step 3: Generate + import .reg file --
set "REGFILE=%TEMP%\labbook-origin-handler.reg"
echo [Step 3] Tao registry file: !REGFILE!
(
  echo Windows Registry Editor Version 5.00
  echo.
  echo [HKEY_CURRENT_USER\Software\Classes\labbook-origin]
  echo @="URL: LabBook Origin Launcher"
  echo "URL Protocol"=""
  echo.
  echo [HKEY_CURRENT_USER\Software\Classes\labbook-origin\DefaultIcon]
  echo @="!ORIGIN_EXE:\=\\!,1"
  echo.
  echo [HKEY_CURRENT_USER\Software\Classes\labbook-origin\shell]
  echo.
  echo [HKEY_CURRENT_USER\Software\Classes\labbook-origin\shell\open]
  echo.
  echo [HKEY_CURRENT_USER\Software\Classes\labbook-origin\shell\open\command]
  echo @="cmd.exe /c \"!WRAPPER:\=\\!\" \"%%1\""
) > "!REGFILE!"

echo [Step 4] Import vao registry...
reg import "!REGFILE!" >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Khong import duoc registry. Hay chay file:
  echo         !REGFILE!
  pause
  exit /b 1
)
echo [OK] Da dang ky 'labbook-origin://' protocol
del "!REGFILE!" >nul 2>&1

echo.
echo ==================================================================
echo  THANH CONG! (Round 97)
echo ==================================================================
echo.
echo Bay gio:
echo   1. Vao web LabBook BKU
echo   2. Click nut 'Mo bang Origin' tren mot file (icon vuong teal)
echo   3. Trinh duyet hoi xac nhan -- chon 'Open' (co the tick
echo      'Always allow' de bo qua lan sau)
echo   4. Origin se mo + tu dong import data + ve plot
echo      (KHONG con mo Code Builder nua nhu Round 96)
echo.
echo De go cai dat: chay uninstall.bat
echo.
pause
