@echo off
REM Auto-generated by LabBook BKU install.bat Round 102
REM Handles labbook-origin protocol launches.
REM Mode 1: data only      labbook-origin://file.xlsx
REM Mode 2: with auto-plot labbook-origin://file.xlsx?withScript=1

setlocal EnableDelayedExpansion
set "ARG=%~1"
set "ORIGIN_EXE=__ORIGIN_EXE__"
set "UFF=__UFF__"

REM Strip protocol prefix
set "FNAME=!ARG:labbook-origin://=!"
if "!FNAME:~-1!"=="/" set "FNAME=!FNAME:~0,-1!"

REM Detect script mode
set "SCRIPT_MODE=0"
echo !FNAME! | findstr /C:"?withScript=1" >nul
if not errorlevel 1 (
  set "SCRIPT_MODE=1"
  set "FNAME=!FNAME:?withScript=1=!"
)

REM URL-decode common chars
set "FNAME=!FNAME:%20= !"
set "FNAME=!FNAME:%28=(!"
set "FNAME=!FNAME:%29=)!"

set "DATAFILE=%USERPROFILE%\Downloads\!FNAME!"
if not exist "!DATAFILE!" (
  echo [ERROR] Data file not found: !DATAFILE!
  echo Hay tai file ve Downloads truoc khi mo Origin.
  pause
  exit /b 1
)

for %%I in ("!DATAFILE!") do set "OGSNAME=%%~nI.ogs"
for %%I in ("!DATAFILE!") do set "BASE=%%~dpnI"
set "OGSFILE=!BASE!.ogs"
set "UFF_OGS=!UFF!\!OGSNAME!"

if "!SCRIPT_MODE!"=="1" if exist "!OGSFILE!" (
  echo [LabBook] Copying script to UFF: !UFF_OGS!
  copy /Y "!OGSFILE!" "!UFF_OGS!" >nul
  if errorlevel 1 (
    echo [WARN] Copy failed - falling back to data-only mode
    start "" "!ORIGIN_EXE!" "!DATAFILE!"
  ) else (
    echo [LabBook] Executing auto-plot script: !OGSNAME!
    start "" "!ORIGIN_EXE!" -rs run.section(!OGSNAME!,Main)
  )
) else (
  echo [LabBook] Launching Origin with data file: !DATAFILE!
  start "" "!ORIGIN_EXE!" "!DATAFILE!"
)
